[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd frontend && npm ci --silent"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npx serve -s build -l $PORT"