-- Add missing property data columns to escrows table

BEGIN;

-- Add property details columns
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS bedrooms INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS bathrooms NUMERIC(3,1);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS square_feet INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS lot_size_sqft INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS year_built INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS garage_spaces INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS stories INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS pool BOOLEAN DEFAULT FALSE;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS spa BOOLEAN DEFAULT FALSE;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS view_type VARCHAR(100);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS architectural_style VARCHAR(100);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS property_condition VARCHAR(50);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS zoning VARCHAR(50);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS apn VARCHAR(50);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS mls_number VARCHAR(50);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS subdivision VARCHAR(100);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS cross_streets VARCHAR(255);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS hoa_fee NUMERIC(10,2);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS hoa_frequency VARCHAR(20);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS hoa_name VARCHAR(100);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS gated_community BOOLEAN DEFAULT FALSE;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS senior_community BOOLEAN DEFAULT FALSE;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS property_features JSONB DEFAULT '{}'::jsonb;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS property_images JSONB DEFAULT '[]'::jsonb;

-- Add financial columns
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS list_price NUMERIC(12,2);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS list_date DATE;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS days_on_market INTEGER;
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS previous_list_price NUMERIC(12,2);
ALTER TABLE escrows ADD COLUMN IF NOT EXISTS original_list_price NUMERIC(12,2);

COMMIT;